import type { Employee, Document, JobListing, Notification } from './types'

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Sarah Johnson',
    role: 'Marketing Manager',
    department: 'Marketing',
    email: 'sarah.johnson@workbenchhr.com',
    startDate: '2023-03-15',
    status: 'active',
    salary: 85000,
  },
  {
    id: 'emp-2',
    name: 'Marcus Williams',
    role: 'Software Engineer',
    department: 'Engineering',
    email: 'marcus.williams@workbenchhr.com',
    startDate: '2022-08-01',
    status: 'active',
    salary: 110000,
  },
  {
    id: 'emp-3',
    name: 'Priya Patel',
    role: 'Operations Lead',
    department: 'Operations',
    email: 'priya.patel@workbenchhr.com',
    startDate: '2021-11-20',
    status: 'active',
    salary: 92000,
  },
  {
    id: 'emp-4',
    name: 'James Chen',
    role: 'Sales Associate',
    department: 'Sales',
    email: 'james.chen@workbenchhr.com',
    startDate: '2024-01-10',
    status: 'active',
    salary: 65000,
  },
  {
    id: 'emp-5',
    name: 'Olivia Martinez',
    role: 'Customer Success',
    department: 'Customer Success',
    email: 'olivia.martinez@workbenchhr.com',
    startDate: '2023-07-05',
    status: 'active',
    salary: 72000,
  },
]

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    title: 'Offer Letter — James Chen',
    type: 'offer_letter',
    employeeId: 'emp-4',
    employeeName: 'James Chen',
    status: 'complete',
    createdAt: '2023-12-20',
  },
  {
    id: 'doc-2',
    title: 'Employment Contract — Olivia Martinez',
    type: 'employment_contract',
    employeeId: 'emp-5',
    employeeName: 'Olivia Martinez',
    status: 'complete',
    createdAt: '2023-06-28',
  },
  {
    id: 'doc-3',
    title: 'Performance Review — Sarah Johnson',
    type: 'performance_review',
    employeeId: 'emp-1',
    employeeName: 'Sarah Johnson',
    status: 'needs_review',
    createdAt: '2024-03-01',
  },
  {
    id: 'doc-4',
    title: 'Onboarding Checklist — James Chen',
    type: 'onboarding_checklist',
    employeeId: 'emp-4',
    employeeName: 'James Chen',
    status: 'pending',
    createdAt: '2024-01-10',
  },
  {
    id: 'doc-5',
    title: 'Performance Review — Marcus Williams',
    type: 'performance_review',
    employeeId: 'emp-2',
    employeeName: 'Marcus Williams',
    status: 'needs_review',
    createdAt: '2024-03-05',
  },
]

export const mockJobListings: JobListing[] = [
  {
    id: 'job-1',
    title: 'Senior Product Designer',
    department: 'Design',
    location: 'Remote',
    type: 'full-time',
    status: 'active',
    postedAt: '2024-02-15',
    applicants: [
      { id: 'app-1', name: 'Alex Rivera', email: 'alex@email.com', stage: 'interview', appliedAt: '2024-02-18' },
      { id: 'app-2', name: 'Dana Kim', email: 'dana@email.com', stage: 'offer', appliedAt: '2024-02-20' },
      { id: 'app-3', name: 'Jordan Lee', email: 'jordan@email.com', stage: 'screening', appliedAt: '2024-02-25' },
      { id: 'app-4', name: 'Taylor Brown', email: 'taylor@email.com', stage: 'applied', appliedAt: '2024-03-01' },
    ],
  },
  {
    id: 'job-2',
    title: 'Account Executive',
    department: 'Sales',
    location: 'New York, NY',
    type: 'full-time',
    status: 'active',
    postedAt: '2024-02-28',
    applicants: [
      { id: 'app-5', name: 'Morgan Ellis', email: 'morgan@email.com', stage: 'screening', appliedAt: '2024-03-02' },
      { id: 'app-6', name: 'Casey Quinn', email: 'casey@email.com', stage: 'applied', appliedAt: '2024-03-05' },
    ],
  },
  {
    id: 'job-3',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'full-time',
    status: 'active',
    postedAt: '2024-03-01',
    applicants: [
      { id: 'app-7', name: 'Sam Torres', email: 'sam@email.com', stage: 'hired', appliedAt: '2024-02-10' },
      { id: 'app-8', name: 'Riley Park', email: 'riley@email.com', stage: 'interview', appliedAt: '2024-03-03' },
    ],
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'review_needed',
    title: 'Performance Reviews Due',
    description: '2 performance reviews are awaiting your approval: Sarah Johnson and Marcus Williams.',
    dueDate: '2024-03-31',
    priority: 'high',
    actionLabel: 'Review Now',
    actionHref: '/documents',
  },
  {
    id: 'notif-2',
    type: 'onboarding',
    title: 'Onboarding Incomplete',
    description: "James Chen's onboarding checklist is 60% complete. Follow up to ensure a smooth start.",
    priority: 'medium',
    actionLabel: 'View Checklist',
    actionHref: '/documents',
  },
  {
    id: 'notif-3',
    type: 'offer_expiring',
    title: 'Offer Expiring Soon',
    description: "Dana Kim's offer for Senior Product Designer expires in 3 days. Reach out to confirm.",
    dueDate: '2024-03-28',
    priority: 'high',
    actionLabel: 'View Candidate',
    actionHref: '/hiring',
  },
]
